name: daily-weather

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build
        run: go build -o bin/weather_push ./cmd/weather_push

      - name: Run (send weather)
        env:
          YAHOO_CLIENT_ID: ${{ secrets.YAHOO_CLIENT_ID }}
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: ./bin/weather_push
